[package]
name = "rusty-von-humboldt"
version = "0.1.0"
authors = ["Matthew Mayer <matthewkmayer@gmail.com>"]

[dependencies]
clap = "2.27"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rayon = "0.9"